name: Build and Publish EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --onefile your_script.py
      # Remplacez `your_script.py` par le nom de votre script Python

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: my-executable
        path: dist/your_script.exe
      # Remplacez `your_script.exe` par le nom de votre exécutable généré
